version: "3.8"

services:
  # --- Backend API ---
  api:
    build: .
    image: resilient-stream-api
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      # Redis servisine 'redis' ismiyle ulaşıyoruz
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      # MongoDB servisine 'mongo' ismiyle ulaşıyoruz
      - MONGO_URI=mongodb://mongo:27017/smartstream
      - JWT_SECRET=d14ae31a3472f106d55af1ec43baf751eefbde2a6370c80113ba0a4b56447ab4f85ee3f2cf169c0cbb9af382d16399304856b3e7deea248e5a35178fffebe8aa
    depends_on:
      - redis
      - mongo
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    networks:
      - smartstream_net
    # Swarm için hazırlık (Hafta 4'te işimize yarayacak)
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  # --- Redis Stack (Cache + Search + JSON) ---
  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"  # Veritabanı portu
      - "8001:8001"  # RedisInsight UI (Görsel Arayüz)
    networks:
      - smartstream_net

  # --- MongoDB (Ana Veritabanı) ---
  mongo:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db # Veriler kaybolmasın diye volume kullanıyoruz
    networks:
      - smartstream_net

# --- Network ve Volume Tanımları ---
networks:
  smartstream_net:
    driver: overlay # Swarm modunda çalışması için overlay seçtik (Localde de çalışır)
    attachable: true  # <--- BU SATIRI EKLEMEN GEREKİYOR
volumes:
  mongo_data: