version: "3.8"

services:
  # Bizim Node.js Uygulamamız
  api:
    build: .
    image: resilient-stream-api
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    # Geliştirme yaparken kod değişince restart etsin diye (Volume Mapping)
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

  # Redis Veritabanı (Session State için)
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
